### ISSUE TITLE
Оптимизировать картинки под разные устройства

### ISSUE THREAD

**Issue by Baregamyan** [Baregamyan/ayrapetyan.art#1]
**Mobile**
Width - 375px - Common Display
Width - 750px - Retina@2x

**Tablet**
Width - 768px - Common Display
Width - 1024px - Retina@2x

**Desktop**
Max Width - 1280px - Common Display
Max Width - 1500px - Retina@2x

**Naming:**
 image-mobile@2x.png
 image-mobile.png

image-tablet@2x.png
image-tablet.png

image-desktop@2x.png
image-desktop.png

**Comment by AinsSpear** [comment]
arachna is done. Kak dobavit' Arsik v git?

**Comment by Baregamyan** [comment]
> arachna is done. Kak dobavit' Arsik v git?

Давай когда все сделаешь, то отправим?

**Comment by AinsSpear** [comment]
Done,
Some pics dont have enough resolution. Later will explain
