### ISSUE TITLE
Придумать Open Graph картинку

### ISSUE THREAD

**Issue by Baregamyan** [Baregamyan/ayrapetyan.art#12]

**Comment by AinsSpear** [comment]
text for opengraph -> Greetings. my nase is Yervand. I am a 3D Artist, specialize in creating various objects, organic and non-organic.

**Comment by AinsSpear** [comment]
Naschet backgrounda dumayu stoit ispolzovat' tot je tip shto na saite. Kartinku eshe norm ne podobral.

**Comment by AinsSpear** [comment]
Opengraph
Greetings. my name is Yervand. I am a 3D Artist, specialize in creating various objects, organic and non-organic.
