### ISSUE TITLE
Добавить pdf файл с резюме для удобства ❓

### ISSUE THREAD

**Issue by Baregamyan** [Baregamyan/ayrapetyan.art#16]
Например, 
![image](https://user-images.githubusercontent.com/31181873/106306960-cde28b00-626f-11eb-9673-02be8bcee771.png)

[Источник](https://lea.verou.me/about/)

**Comment by AinsSpear** [comment]
resume updated, pdf created, uploaded to gdrive

**Comment by Baregamyan** [comment]
> resume updated, pdf created, uploaded to gdrive

Давай оформим симпотично? 

https://resume.io/app/
https://novoresume.com/
https://resumegenius.com/

Все бесплатные. **Resume.io** я даже зарегался быстренько и скачал =)

**Comment by AinsSpear** [comment]
Arsen dai plz primer kak ti resume vidish, linki eti s CV chestno govorya viju v nih pustotu
